#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_ROOT="${ROOT_DIR}"
CODEX_HOME_TARGET="${CODEX_HOME:-$HOME/.codex}"
PROFILE_NAME="amax"
PYTHON_CMD="${PYTHON_CMD:-python3}"
STORE_ROOT=""
FORCE=0
DRY_RUN=0

usage() {
  cat <<'EOF'
Usage:
  ./scripts/bootstrap-friend-codex.sh [options]

Options:
  --codex-home <path>   Target Codex home (default: $CODEX_HOME or ~/.codex)
  --repo-root <path>    Repo root path (default: auto-detected)
  --profile <name>      Distribution profile suffix (default: amax)
  --store-root <path>   Runtime store root (default: <codex-home>/runtime-spike-<profile>)
  --python-cmd <cmd>    Python command used by wrapper (default: python3)
  --force               Overwrite existing files created by this installer
  --dry-run             Print planned actions only
  -h, --help            Show help

Notes:
  - Installer is non-destructive by default. Existing files are never overwritten unless --force is set.
  - Files are installed under profile-specific paths so existing ~/.codex setup can coexist.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --codex-home)
      CODEX_HOME_TARGET="$2"
      shift 2
      ;;
    --repo-root)
      REPO_ROOT="$2"
      shift 2
      ;;
    --profile)
      PROFILE_NAME="$2"
      shift 2
      ;;
    --store-root)
      STORE_ROOT="$2"
      shift 2
      ;;
    --python-cmd)
      PYTHON_CMD="$2"
      shift 2
      ;;
    --force)
      FORCE=1
      shift
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "[bootstrap-friend-codex] unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ ! "${PROFILE_NAME}" =~ ^[A-Za-z0-9_-]+$ ]]; then
  echo "[bootstrap-friend-codex] --profile must match [A-Za-z0-9_-]+" >&2
  exit 2
fi

if [[ -z "${STORE_ROOT}" ]]; then
  STORE_ROOT="${CODEX_HOME_TARGET}/runtime-spike-${PROFILE_NAME}"
fi

RUNTIME_DIR="${CODEX_HOME_TARGET}/runtime-adapter-${PROFILE_NAME}"
ENV_PATH="${RUNTIME_DIR}/runtime-adapter-${PROFILE_NAME}.env"
WRAPPER_PATH="${RUNTIME_DIR}/codex-runtime-${PROFILE_NAME}"
CONTRACT_PATH="${RUNTIME_DIR}/verifier-contract.md"
MANIFEST_PATH="${RUNTIME_DIR}/install-manifest.json"

SKILL_DIR="${CODEX_HOME_TARGET}/skills/runtime-adapter-ops-${PROFILE_NAME}"
SKILL_PATH="${SKILL_DIR}/SKILL.md"

AGENTS_DIR="${CODEX_HOME_TARGET}/agents"
COORDINATOR_PATH="${AGENTS_DIR}/coordinator-${PROFILE_NAME}.toml"
VERIFIER_PATH="${AGENTS_DIR}/verifier-${PROFILE_NAME}.toml"

log() {
  echo "[bootstrap-friend-codex] $*"
}

write_file() {
  local path="$1"
  local mode="$2"
  local content="$3"
  if [[ -e "${path}" && ${FORCE} -ne 1 ]]; then
    log "skip (exists): ${path}"
    return 0
  fi
  if [[ ${DRY_RUN} -eq 1 ]]; then
    log "dry-run write: ${path}"
    return 0
  fi
  mkdir -p "$(dirname "${path}")"
  local tmp
  tmp="$(mktemp "${path}.tmp.XXXX")"
  printf "%s" "${content}" > "${tmp}"
  chmod "${mode}" "${tmp}"
  mv "${tmp}" "${path}"
  log "wrote: ${path}"
}

render_agent_with_name() {
  local source_toml="$1"
  local target_name="$2"
  "${PYTHON_CMD}" - "${source_toml}" "${target_name}" <<'PY'
import re
import sys
from pathlib import Path

source_path = Path(sys.argv[1])
target_name = sys.argv[2]
text = source_path.read_text(encoding="utf-8")
updated = re.sub(r'^name\s*=\s*".*?"\s*$', f'name = "{target_name}"', text, count=1, flags=re.MULTILINE)
print(updated, end="")
PY
}

if [[ ! -f "${REPO_ROOT}/poc/codex_runtime_adapter.py" ]]; then
  echo "[bootstrap-friend-codex] adapter not found under repo root: ${REPO_ROOT}" >&2
  exit 2
fi
if [[ ! -f "${REPO_ROOT}/coordinator.toml" || ! -f "${REPO_ROOT}/verifier.toml" ]]; then
  echo "[bootstrap-friend-codex] coordinator/verifier toml not found in repo root" >&2
  exit 2
fi
if [[ ! -f "${REPO_ROOT}/verifier-contract.md" ]]; then
  echo "[bootstrap-friend-codex] verifier-contract.md not found in repo root" >&2
  exit 2
fi

ENV_CONTENT=$(cat <<EOF
# Generated by scripts/bootstrap-friend-codex.sh
# Profile: ${PROFILE_NAME}

export AMAX_PROFILE_NAME="${PROFILE_NAME}"
export AMAX_REPO_ROOT="${REPO_ROOT}"
export AMAX_PYTHON_CMD="${PYTHON_CMD}"
export AMAX_RUNTIME_ADAPTER_PATH="\${AMAX_REPO_ROOT}/poc/codex_runtime_adapter.py"
export AMAX_RUNTIME_STORE_ROOT="${STORE_ROOT}"
export AMAX_RUNTIME_WRAPPER_PATH="${WRAPPER_PATH}"
export AMAX_VERIFIER_CONTRACT_PATH="${CONTRACT_PATH}"
export AMAX_RECOVERY_PLAYBOOK_PATH="\${AMAX_REPO_ROOT}/docs/recovery-playbook.md"

# Helper/orchestrator path overrides for portability
export CODEX_RUNTIME_HELPER_RUNTIME_CMD="\${AMAX_RUNTIME_WRAPPER_PATH}"
export CODEX_ORCH_SESSION_SCRIPT="\${AMAX_REPO_ROOT}/poc/session_helper.py"
export CODEX_ORCH_TASK_UPDATE_NOTIFY_SCRIPT="\${AMAX_REPO_ROOT}/poc/task_update_notify_helper.py"
export CODEX_ORCH_POST_CHECK_SCRIPT="\${AMAX_REPO_ROOT}/poc/post_step_check_helper.py"
export CODEX_ORCH_COMPUTER_USE_SCRIPT="\${AMAX_REPO_ROOT}/poc/computer_use_helper.py"
export CODEX_ORCH_VERIFIER_GATE_SCRIPT="\${AMAX_REPO_ROOT}/poc/verifier_gate_helper.py"
export CODEX_ORCH_BRIDGE_SCRIPT="\${AMAX_REPO_ROOT}/poc/bridge_helper.py"
export CODEX_ORCH_LOOPBACK_SCRIPT="\${AMAX_REPO_ROOT}/poc/loopback_helper.py"
export CODEX_ORCH_CHAIN_SCRIPT="\${AMAX_REPO_ROOT}/poc/chain_helper.py"

# Optional convenience alias (does not override existing codex-runtime)
alias codex-runtime-${PROFILE_NAME}="\${AMAX_RUNTIME_WRAPPER_PATH}"
EOF
)

WRAPPER_TEMPLATE_PATH="${REPO_ROOT}/scripts/templates/codex-runtime-wrapper.template.sh"
if [[ ! -f "${WRAPPER_TEMPLATE_PATH}" ]]; then
  echo "[bootstrap-friend-codex] wrapper template not found: ${WRAPPER_TEMPLATE_PATH}" >&2
  exit 2
fi
WRAPPER_CONTENT="$(cat "${WRAPPER_TEMPLATE_PATH}")"
WRAPPER_CONTENT="${WRAPPER_CONTENT//__PROFILE_NAME__/${PROFILE_NAME}}"
WRAPPER_CONTENT="${WRAPPER_CONTENT//__REPO_ROOT__/${REPO_ROOT}}"
WRAPPER_CONTENT="${WRAPPER_CONTENT//__STORE_ROOT__/${STORE_ROOT}}"

SKILL_CONTENT=$(cat <<EOF
---
name: "runtime-adapter-ops-${PROFILE_NAME}"
description: "Use when operating AI Agent Maximizer runtime adapter via profile-specific wrapper under ${CODEX_HOME_TARGET}."
---

# Runtime Adapter Ops (${PROFILE_NAME})

## Setup

1. Load profile env:
   - \`source "${ENV_PATH}"\`
2. Run wrapper directly:
   - \`${WRAPPER_PATH} ops\`

## Quick Commands

- Team create:
  - \`${WRAPPER_PATH} team-create "alpha" "alpha-1"\`
- Send direct message:
  - \`${WRAPPER_PATH} send-message <team_id> <from_member_id> <to_member_id> "hello" "msg-1"\`
- Task create:
  - \`${WRAPPER_PATH} task-create <team_id> "first task" <owner_member_id> ready "task-1"\`
- Runtime reconcile:
  - \`${WRAPPER_PATH} reconcile-all\`

## Fail-open vs Strict

- Default is fail-open JSON envelope.
- Strict mode: prefix \`--strict\`.
  - Example: \`${WRAPPER_PATH} --strict reconcile-all\`
EOF
)

COORDINATOR_CONTENT="$(render_agent_with_name "${REPO_ROOT}/coordinator.toml" "coordinator-${PROFILE_NAME}")"
VERIFIER_CONTENT="$(render_agent_with_name "${REPO_ROOT}/verifier.toml" "verifier-${PROFILE_NAME}")"
CONTRACT_CONTENT="$(cat "${REPO_ROOT}/verifier-contract.md")"

MANIFEST_CONTENT="$("${PYTHON_CMD}" - "${REPO_ROOT}" "${CODEX_HOME_TARGET}" "${PROFILE_NAME}" "${ENV_PATH}" "${WRAPPER_PATH}" "${SKILL_PATH}" "${COORDINATOR_PATH}" "${VERIFIER_PATH}" "${CONTRACT_PATH}" "${STORE_ROOT}" <<'PY'
import json
import sys
repo_root, codex_home, profile, env_path, wrapper_path, skill_path, coordinator_path, verifier_path, contract_path, store_root = sys.argv[1:]
obj = {
    "profile": profile,
    "repo_root": repo_root,
    "codex_home": codex_home,
    "store_root": store_root,
    "installed_files": {
        "runtime_env": env_path,
        "runtime_wrapper": wrapper_path,
        "skill": skill_path,
        "coordinator_agent": coordinator_path,
        "verifier_agent": verifier_path,
        "verifier_contract_copy": contract_path,
    },
}
print(json.dumps(obj, ensure_ascii=False, indent=2))
PY
)"

log "target codex home: ${CODEX_HOME_TARGET}"
log "profile: ${PROFILE_NAME}"
log "repo root: ${REPO_ROOT}"
log "store root: ${STORE_ROOT}"

write_file "${ENV_PATH}" 0644 "${ENV_CONTENT}"
write_file "${WRAPPER_PATH}" 0755 "${WRAPPER_CONTENT}"
write_file "${SKILL_PATH}" 0644 "${SKILL_CONTENT}"
write_file "${COORDINATOR_PATH}" 0644 "${COORDINATOR_CONTENT}"
write_file "${VERIFIER_PATH}" 0644 "${VERIFIER_CONTENT}"
write_file "${CONTRACT_PATH}" 0644 "${CONTRACT_CONTENT}"
write_file "${MANIFEST_PATH}" 0644 "${MANIFEST_CONTENT}"

log "done"
log "next:"
log "  source \"${ENV_PATH}\""
log "  \"${WRAPPER_PATH}\" ops"
